---

    - name: ENABLE FEATURES
      nxos_feature:
        feature: "{{item.feature }}"
        provider: "{{ nxos_provider }}"
      with_items: "{{ features }}"

    - name: CONFIGURE PHYSICAL L3 INTERFACES
      nxos_interface:
        interface: "{{item.interface }}"
        mode: layer3
        admin_state: up
        provider: "{{ nxos_provider }}"
      with_items: "{{ l3_interfaces }}"

    - name: CONFIGURE LOOPBACK INTERFACES
      nxos_interface:
        interface: "{{ item.interface }}"
        provider: "{{ nxos_provider }}"
      with_items: "{{ loopbacks }}"

    - name: CONFIGURE INTERFACE IP ADDR
      nxos_ip_interface:
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        provider: "{{ nxos_provider }}"
      with_items: 
      - "{{ loopbacks }}"
      - "{{ l3_interfaces }}"

    - name: CONFIGURE OSPF PROCESS ID + AREA + ROUTER ID
      nxos_ospf_vrf:
        ospf: "{{ ospf_process_id }}"
        router_id: "{{ router_id }}"
        provider: "{{ nxos_provider }}"

    - name: ASSOCIATE INTERFACES WITH OSPF PROCESS
      nxos_interface_ospf:
        interface: "{{ item.interface }}"
        ospf: "{{ ospf_process_id }}"
        area: "{{ ospf_area }}"
        provider: "{{ nxos_provider }}"
      with_items: 
      - "{{ l3_interfaces }}"
      - "{{ loopbacks }}"

    - name: CONFIGURE OSPF INTERFACES NETWORK P2P
      nxos_config:
        lines: ip ospf network point-to-point
        parents:
          - 'interface {{ item.interface }}'
        provider: "{{ nxos_provider  }}"
      with_items: "{{ l3_interfaces }}"

    - name: CONFIGURE PIM RP
      nxos_pim_rp_address:
        rp_address: "{{ rp_address }}"
        provider: "{{ nxos_provider }}"

    - name: CONFIGURE PIM INTERFACES
      nxos_pim_interface:
        interface: "{{ item.interface }}"
        sparse: true
        provider: "{{ nxos_provider }}"
      with_items: "{{ l3_interfaces }}"
